### ISSUE TITLE
New version of dbus

### ISSUE THREAD

**Issue by colonelpanic8** [portnov/dbus-th-introspection#2]
I recently added client generation with signal and property support to the dbus library (and made several other very significant changes to the library).

This duplicates the functionality of this library, which I realize might be frustrating to you, but it might make some things easier to support moving forward.

Thought I'd give you a heads up just because id like to get the new dbus version in to stackage, and it needs this libarary to upgrade to the new dbus version.

**Comment by portnov** [comment]
Thanks for the information! :)

**Comment by portnov** [comment]
@IvanMalison is there any documentation for these new features, or changelog? Could not find one.

**Comment by colonelpanic8** [comment]
@portnov none yet. You can look at https://github.com/IvanMalison/status-notifier-item

And specifically

https://github.com/IvanMalison/status-notifier-item/blob/master/src/StatusNotifier/Item/Client.hs

and

https://github.com/IvanMalison/status-notifier-item/blob/master/src/StatusNotifier/Watcher/Client.hs

to see them in action.

**Comment by portnov** [comment]
Well, I prefer to have description of dbus interface in EDSL-style.  Let a hundred flowers bloom, anyone is free to use approach which he likes more :) So, I just updated this package and dbus-th package to work with current version of dbus. In dbus-th package, I also renamed DBus.TH module to DBus.TH.EDSL to avoid name clash with dbus package.
